name: Publish to NuGet

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    name: Update NuGet
    environment: Dev
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
        
      - name: Build Solution and Generate Package
        run: |
          cd NoSQLTransactionalOutbox.Core
          dotnet pack -c Release -o out
          
      - name: Install Nuget
        uses: nuget/setup-nuget@v1
        
      - name: Add Private GitHub Repo to NuGet

        # run: nuget sources add -name "GPR" -Source https://nuget.pkg.github.com/mjlindsay/index.json -Username mjlindsay -Password ${{secrets.GITHUB_TOKEN}}
        run: dotnet nuget add source --username mjlindsay --password ${{ secrets.NUGET_PACKAGE_KEY }} --store-password-in-clear-text --name GPR "https://nuget.pkg.github.com/mjlindsay/index.json" 
      
      - name: Push Generated Package
        run: dotnet nuget push .\NoSqlTransactionalOutbox.Core\out\*.nupkg --source "GPR" --skip-duplicate
